### ISSUE TITLE
provider virtualbox broken for 2016.01.01

### ISSUE THREAD

**Issue by billryan** [Dreamscapes/atlas-archlinux#1]
md5sum of the downloaded virtualbox.box(19MB): `ed58224d5becb3f78ce891f114c99db5`

**Comment by robertrossmann** [comment]
Thanks for the warning! On Atlas, the size is displayed correctly, so I did not notice. Uploading the box again. I will notify you once it has been uploaded.

**Comment by robertrossmann** [comment]
Done! Let me know if there are still issues. Thanks!
